// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.shirtBotJon.subsystems;

import org.usfirst.frc0.shirtBotJon.Robot;
import org.usfirst.frc0.shirtBotJon.RobotMap;
import org.usfirst.frc0.shirtBotJon.commands.*;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class driveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftFront = RobotMap.driveTrainleftFront;
    private final SpeedController leftBack = RobotMap.driveTrainleftBack;
    private final SpeedController rightFront = RobotMap.driveTrainrightFront;
    private final SpeedController rightBack = RobotMap.driveTrainrightBack;
    private final AnalogGyro driveGyro = RobotMap.driveTraindriveGyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void drive() {
    	//this is a basic mecanum drive. it takes raw xy input
    	final double x = Robot.oi.joystick.getX();
    	final double y = Robot.oi.joystick.getY();
    	final double z = Robot.oi.joystick.getZ();
    	Robot.robotDrive.mecanumDrive_Cartesian(x, y, z, 0);
    }
    public void stop(){
    	Robot.robotDrive.mecanumDrive_Cartesian(0,0,0,0);
    }
    public void destroyEverything() {
    	System.out.println("Test method!");
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
}

